name: 'espcd action'
description: 'compiles and uploads arduino sketch to espcd-backend'
inputs:
  url:
    description: 'The url of the backend firmwares path'
    required: true
    default: 'https://api.espcd.duckdns.org/firmwares'
  api_key:
    description: 'An api key for access to the backend'
    required: true
  fqbn:
    description: 'The fully qualified board name of the device, e.g.: esp8266:esp8266:generic'
    required: true
  sketch:
    description: 'Path to the arduino sketch that should be compiled'
    required: true
  product:
    description: 'The id of the product that should be assiciated with the firmware'
    required: false
  title:
    description: 'The title of the firmware'
    required: false
    default: ''
  description:
    description: 'The description of the firmware'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_API_KEY: ${{ inputs.api_key }}
        INPUT_FQBN: ${{ inputs.fqbn }}
        INPUT_SKETCH: ${{ inputs.sketch }}
        INPUT_PRODUCT: ${{ inputs.product }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_DESCRIPTION: ${{ inputs.description }}
